---
ID: "fee0ccba-3c8a-419a-ad77-8c71ed06698a"
Parent: "2766bcbf-7430-4b66-8fc0-d1646e11b14c"
Template: "2fcdc739-f535-40cb-af2b-c7edd0b0ddc5"
Path: "/sitecore/content/sitecorecdp/home/products/product-2"
DB: master
SharedFields:
- ID: "9135200a-5626-4dd8-ab9d-d665b8c11748"
  Hint: __Never publish
  Type: checkbox
  Value: 1
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Product 2
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220806T032119Z
    - ID: "a0a4d9b7-2798-4f5c-93a8-bd661b2c1d01"
      Hint: CodeDescTitle
      Value: "product-2"
