---
ID: "5a6cd948-176f-4e8d-bae4-ff8e304597e7"
Parent: "53e0bcc1-c1ad-4531-8562-7e1a831f00fa"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Project/sitecorecdp/pim/Product
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220806T062501Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
