---
ID: "116685af-fa12-44df-8a1e-987fc3fb5dc2"
Parent: "21a67b50-25e1-4e6b-b2db-c82bfe7a04bd"
Template: "21a67b50-25e1-4e6b-b2db-c82bfe7a04bd"
Path: /sitecore/templates/Project/sitecorecdp/tabpage/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {2FCDC739-F535-40CB-AF2B-C7EDD0B0DDC5}
    {4EEE653B-2D07-439E-8358-1DA97C3895CB}
    {21A67B50-25E1-4E6B-B2DB-C82BFE7A04BD}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220802T082447Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8973a831-fe5e-49a0-9db9-306131dfdce1"
      Hint: heading
      Value: $name
